[package]
name = "day18"
version = "0.1.0"
authors = ["Michael Pyle <mpyle101@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
pathfinding = "2.1.4"
