[package]
name = "day11"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-iter = "1.1.1"
indexmap = "1.9.2"
itertools = "0.10.3"
rustc-hash = "1.1.0"